//add products
let products = [
  {
    img: "f1.jpg",
    title: "cartoon astronout t-shirt",
    company: "adidas",
    id: "76152552",
    price: "90",
  },
  {
    img: "f2.jpg",
    title: "cartoon astronout t-shirt",
    company: "nike",
    id: "333344343",
    price: "90",
  },
  {
    img: "f3.jpg",
    title: "cartoon astronout t-shirt",
    company: "aldo",
    id: "7615254452",
    price: "60",
  },
  {
    img: "f4.jpg",
    title: "cartoon astronout t-shirt",
    company: "aldo",
    id: "4455555343",
    price: "70",
  },
  {
    img: "f5.jpg",
    title: "cartoon astronout t-shirt",
    company: "adidas",
    id: "7hahsha7262656",
    price: "20",
  },
  {
    img: "f6.jpg",
    title: "cartoon astronout t-shirt",
    company: "adidas",
    id: "3775444477",
    price: "90",
  },
  {
    img: "f7.jpg",
    title: "cartoon astronout t-shirt",
    company: "adidas",
    id: "11233456",
    price: "90",
  },
  {
    img: "f8.jpg",
    title: "cartoon astronout t-shirt",
    company: "adidas",
    id: "98876765",
    price: "34",
  },
  {
    img: "n1.jpg",
    title: "cartoon astronout t-shirt",
    company: "nike",
    id: "6787ikkk",
    price: "56",
  },
  {
    img: "n2.jpg",
    title: "cartoon astronout t-shirt",
    company: "adidas",
    id: "0956787765",
    price: "90",
  },
  {
    img: "n3.jpg",
    title: "cartoon astronout t-shirt",
    company: "adidas",
    id: "qweerrrtt3232",
    price: "50",
  },
  {
    img: "n4.jpg",
    title: "cartoon astronout t-shirt",
    company: "splash",
    id: "rffr445555",
    price: "70",
  },
  {
    img: "n5.jpg",
    title: "cartoon astronout t-shirt",
    company: "splash",
    id: "kjgggfg1222",
    price: "87",
  },
  {
    img: "n6.jpg",
    title: "cartoon astronout t-shirt",
    company: "adidas",
    id: "zxcvff33",
    price: "90",
  },
  {
    img: "n7.jpg",
    title: "cartoon astronout t-shirt",
    company: "adidas",
    id: "ghyt55656gg",
    price: "40",
  },
  {
    img: "n8.jpg",
    title: "cartoon astronout t-shirt",
    company: "adidas",
    id: "45rt54rt54r",
    price: "91",
  },
];
